import type { 
  Product, 
  Warehouse, 
  Location, 
  InventoryItem, 
  StockMovement,
  Vendor, 
  Garment, 
  PurchaseOrder, 
  DeliveryOrder,
  Receiving,
  DashboardStats,
  RecentActivity,
  ChartData
} from '@/types';

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'SKU-001',
    barcode: '8901234567890',
    name: 'Cotton Fabric Roll - White',
    category: 'Raw Materials',
    unit: 'Roll',
    color: 'White',
    size: '150cm',
    price: 500000,
    stock: 250,
    minStock: 50,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '2',
    sku: 'SKU-002',
    barcode: '8901234567891',
    name: 'Polyester Thread - Black',
    category: 'Accessories',
    unit: 'Spool',
    color: 'Black',
    size: '500m',
    price: 15000,
    stock: 1000,
    minStock: 200,
    status: 'active',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: '3',
    sku: 'SKU-003',
    barcode: '8901234567892',
    name: 'Jersey Fabric - Navy Blue',
    category: 'Raw Materials',
    unit: 'Meter',
    color: 'Navy Blue',
    size: '180cm',
    price: 75000,
    stock: 45,
    minStock: 100,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-14'),
  },
  {
    id: '4',
    sku: 'SKU-004',
    barcode: '8901234567893',
    name: 'Zipper YKK - Silver',
    category: 'Accessories',
    unit: 'Piece',
    color: 'Silver',
    size: '20cm',
    price: 5000,
    stock: 500,
    minStock: 100,
    status: 'active',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '5',
    sku: 'SKU-005',
    barcode: '8901234567894',
    name: 'Hoodie Blank - Gray',
    category: 'Finished Goods',
    unit: 'Piece',
    color: 'Gray',
    size: 'L',
    price: 85000,
    stock: 150,
    minStock: 30,
    status: 'active',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: '6',
    sku: 'SKU-006',
    barcode: '8901234567895',
    name: 'Button Metal - Bronze',
    category: 'Accessories',
    unit: 'Piece',
    color: 'Bronze',
    size: '15mm',
    price: 2000,
    stock: 2000,
    minStock: 500,
    status: 'active',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-17'),
  },
  {
    id: '7',
    sku: 'SKU-007',
    barcode: '8901234567896',
    name: 'Packaging Box - Medium',
    category: 'Packaging',
    unit: 'Piece',
    color: 'Brown',
    size: '30x20x15cm',
    price: 8000,
    stock: 800,
    minStock: 200,
    status: 'active',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: '8',
    sku: 'SKU-008',
    barcode: '8901234567897',
    name: 'T-Shirt Blank - White',
    category: 'Finished Goods',
    unit: 'Piece',
    color: 'White',
    size: 'M',
    price: 45000,
    stock: 20,
    minStock: 50,
    status: 'active',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-03-19'),
  },
];

// Mock Warehouses
export const mockWarehouses: Warehouse[] = [
  {
    id: '1',
    name: 'Main Warehouse',
    code: 'WH-001',
    address: 'Jl. Industri No. 123, Jakarta',
    capacity: 10000,
    usedCapacity: 7500,
    status: 'active',
  },
  {
    id: '2',
    name: 'Secondary Warehouse',
    code: 'WH-002',
    address: 'Jl. Gudang No. 456, Tangerang',
    capacity: 5000,
    usedCapacity: 3200,
    status: 'active',
  },
  {
    id: '3',
    name: 'Distribution Center',
    code: 'WH-003',
    address: 'Jl. Distribusi No. 789, Bekasi',
    capacity: 8000,
    usedCapacity: 4500,
    status: 'active',
  },
];

// Mock Locations
export const mockLocations: Location[] = [
  { id: '1', warehouseId: '1', zone: 'A', rack: 'A1', shelf: '01', binCode: 'A1-01-001', capacity: 100, usedCapacity: 75 },
  { id: '2', warehouseId: '1', zone: 'A', rack: 'A1', shelf: '02', binCode: 'A1-01-002', capacity: 100, usedCapacity: 80 },
  { id: '3', warehouseId: '1', zone: 'A', rack: 'A2', shelf: '01', binCode: 'A2-01-001', capacity: 150, usedCapacity: 120 },
  { id: '4', warehouseId: '1', zone: 'B', rack: 'B1', shelf: '01', binCode: 'B1-01-001', capacity: 200, usedCapacity: 150 },
  { id: '5', warehouseId: '2', zone: 'A', rack: 'A1', shelf: '01', binCode: 'A1-01-001', capacity: 100, usedCapacity: 60 },
  { id: '6', warehouseId: '2', zone: 'A', rack: 'A1', shelf: '02', binCode: 'A1-01-002', capacity: 100, usedCapacity: 90 },
];

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    id: '1',
    code: 'VND-001',
    name: 'PT Textile Indonesia',
    companyName: 'PT Textile Indonesia Makmur',
    picName: 'Budi Santoso',
    email: 'budi@textileindonesia.com',
    phone: '+62812345678',
    address: 'Jl. Tekstil No. 100',
    city: 'Bandung',
    vendorType: 'Fabric Supplier',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '2',
    code: 'VND-002',
    name: 'CV Aksesoris Jaya',
    companyName: 'CV Aksesoris Jaya Abadi',
    picName: 'Siti Rahayu',
    email: 'siti@aksesorisjaya.com',
    phone: '+62823456789',
    address: 'Jl. Aksesoris No. 50',
    city: 'Jakarta',
    vendorType: 'Accessories Supplier',
    status: 'active',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '3',
    code: 'VND-003',
    name: 'Print Master',
    companyName: 'PT Print Master Indonesia',
    picName: 'Ahmad Rizki',
    email: 'ahmad@printmaster.com',
    phone: '+62834567890',
    address: 'Jl. Sablon No. 25',
    city: 'Surabaya',
    vendorType: 'Printing Vendor',
    status: 'active',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    code: 'VND-004',
    name: 'Bordir Indah',
    companyName: 'UD Bordir Indah',
    picName: 'Dewi Lestari',
    email: 'dewi@bordirindah.com',
    phone: '+62845678901',
    address: 'Jl. Bordir No. 75',
    city: 'Yogyakarta',
    vendorType: 'Embroidery Vendor',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '5',
    code: 'VND-005',
    name: 'Pack Solution',
    companyName: 'PT Pack Solution Indonesia',
    picName: 'Eko Prasetyo',
    email: 'eko@packsolution.com',
    phone: '+62856789012',
    address: 'Jl. Kemasan No. 30',
    city: 'Semarang',
    vendorType: 'Packaging Vendor',
    status: 'active',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-20'),
  },
];

// Mock Garments/Clients
export const mockGarments: Garment[] = [
  {
    id: '1',
    code: 'GRM-001',
    name: 'SportWear Pro',
    brand: 'SportWear',
    picName: 'John Smith',
    email: 'john@sportwear.com',
    phone: '+62811111111',
    address: 'Jl. Sport No. 1, Jakarta',
    productionType: 'Jersey',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '2',
    code: 'GRM-002',
    name: 'Urban Style',
    brand: 'Urban',
    picName: 'Maria Garcia',
    email: 'maria@urbanstyle.com',
    phone: '+62822222222',
    address: 'Jl. Fashion No. 2, Bandung',
    productionType: 'Hoodie',
    status: 'active',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '3',
    code: 'GRM-003',
    name: 'Basic Tees',
    brand: 'BasicTee',
    picName: 'David Lee',
    email: 'david@basictees.com',
    phone: '+62833333333',
    address: 'Jl. Casual No. 3, Surabaya',
    productionType: 'T-Shirt',
    status: 'active',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    code: 'GRM-004',
    name: 'Corporate Wear',
    brand: 'CorpWear',
    picName: 'Lisa Wong',
    email: 'lisa@corporatewear.com',
    phone: '+62844444444',
    address: 'Jl. Formal No. 4, Jakarta',
    productionType: 'Polo',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-15'),
  },
];

// Mock Purchase Orders
export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: '1',
    poNumber: 'PO-2024-001',
    vendorId: '1',
    vendor: mockVendors[0],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    orderDate: new Date('2024-03-01'),
    expectedDate: new Date('2024-03-15'),
    status: 'Approved',
    items: [
      { id: '1', productId: '1', product: mockProducts[0], quantity: 100, unit: 'Roll', price: 500000, total: 50000000, receivedQuantity: 0 },
      { id: '2', productId: '2', product: mockProducts[1], quantity: 500, unit: 'Spool', price: 15000, total: 7500000, receivedQuantity: 0 },
    ],
    totalAmount: 57500000,
    notes: 'Urgent order for Q2 production',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '2',
    poNumber: 'PO-2024-002',
    vendorId: '2',
    vendor: mockVendors[1],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    orderDate: new Date('2024-03-05'),
    expectedDate: new Date('2024-03-20'),
    status: 'Partial Received',
    items: [
      { id: '3', productId: '4', product: mockProducts[3], quantity: 1000, unit: 'Piece', price: 5000, total: 5000000, receivedQuantity: 500 },
      { id: '4', productId: '6', product: mockProducts[5], quantity: 2000, unit: 'Piece', price: 2000, total: 4000000, receivedQuantity: 1000 },
    ],
    totalAmount: 9000000,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: '3',
    poNumber: 'PO-2024-003',
    vendorId: '5',
    vendor: mockVendors[4],
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    orderDate: new Date('2024-03-10'),
    expectedDate: new Date('2024-03-25'),
    status: 'Draft',
    items: [
      { id: '5', productId: '7', product: mockProducts[6], quantity: 500, unit: 'Piece', price: 8000, total: 4000000, receivedQuantity: 0 },
    ],
    totalAmount: 4000000,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    poNumber: 'PO-2024-004',
    vendorId: '1',
    vendor: mockVendors[0],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    orderDate: new Date('2024-02-15'),
    expectedDate: new Date('2024-03-01'),
    status: 'Completed',
    items: [
      { id: '6', productId: '3', product: mockProducts[2], quantity: 200, unit: 'Meter', price: 75000, total: 15000000, receivedQuantity: 200 },
    ],
    totalAmount: 15000000,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-02'),
  },
];

// Mock Delivery Orders
export const mockDeliveryOrders: DeliveryOrder[] = [
  {
    id: '1',
    doNumber: 'DO-2024-001',
    garmentId: '1',
    garment: mockGarments[0],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    deliveryDate: new Date('2024-03-20'),
    status: 'Picking',
    items: [
      { id: '1', productId: '3', product: mockProducts[2], availableStock: 45, requestedQuantity: 30, allocatedQuantity: 30 },
      { id: '2', productId: '2', product: mockProducts[1], availableStock: 1000, requestedQuantity: 200, allocatedQuantity: 200 },
    ],
    notes: 'Priority shipment for sports event',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: '2',
    doNumber: 'DO-2024-002',
    garmentId: '2',
    garment: mockGarments[1],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    deliveryDate: new Date('2024-03-22'),
    status: 'Draft',
    items: [
      { id: '3', productId: '5', product: mockProducts[4], availableStock: 150, requestedQuantity: 50, allocatedQuantity: 0 },
    ],
    createdAt: new Date('2024-03-16'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: '3',
    doNumber: 'DO-2024-003',
    garmentId: '3',
    garment: mockGarments[2],
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    deliveryDate: new Date('2024-03-18'),
    status: 'Shipped',
    items: [
      { id: '4', productId: '8', product: mockProducts[7], availableStock: 20, requestedQuantity: 15, allocatedQuantity: 15 },
    ],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-17'),
  },
];

// Mock Inventory Items
export const mockInventoryItems: InventoryItem[] = mockProducts.map((product, index) => ({
  id: `inv-${index + 1}`,
  productId: product.id,
  product,
  warehouseId: index % 2 === 0 ? '1' : '2',
  warehouse: index % 2 === 0 ? mockWarehouses[0] : mockWarehouses[1],
  locationId: mockLocations[index % mockLocations.length].id,
  location: mockLocations[index % mockLocations.length],
  availableStock: product.stock,
  reservedStock: Math.floor(product.stock * 0.1),
  incomingStock: Math.floor(Math.random() * 50),
  outgoingStock: Math.floor(Math.random() * 30),
  lastUpdated: new Date(),
}));

// Mock Stock Movements (Enhanced with Source Type and Status)
export const mockStockMovements: StockMovement[] = [
  {
    id: '1',
    transactionId: 'TRX-2024-001',
    productId: '1',
    product: mockProducts[0],
    movementType: 'INBOUND',
    sourceType: 'PURCHASE_ORDER',
    quantity: 100,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '1',
    location: mockLocations[0],
    referenceNumber: 'PO-2024-001',
    vendorId: '1',
    vendor: mockVendors[0],
    purchaseOrderId: '1',
    userId: 'user-1',
    userName: 'Admin User',
    status: 'Posted',
    timestamp: new Date('2024-03-15T10:30:00'),
    notes: 'Received from PO-2024-001',
  },
  {
    id: '2',
    transactionId: 'TRX-2024-002',
    productId: '3',
    product: mockProducts[2],
    movementType: 'OUTBOUND',
    sourceType: 'DELIVERY_ORDER',
    quantity: 30,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '3',
    location: mockLocations[2],
    referenceNumber: 'DO-2024-001',
    garmentId: '1',
    garment: mockGarments[0],
    deliveryOrderId: '1',
    userId: 'user-2',
    userName: 'Warehouse Staff',
    status: 'Posted',
    timestamp: new Date('2024-03-16T14:15:00'),
    notes: 'Shipped for DO-2024-001',
  },
  {
    id: '3',
    transactionId: 'TRX-2024-003',
    productId: '5',
    product: mockProducts[4],
    movementType: 'ADJUSTMENT',
    sourceType: 'ADJUSTMENT',
    quantity: -5,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '1',
    location: mockLocations[0],
    adjustmentReason: 'Stock count discrepancy',
    userId: 'user-1',
    userName: 'Admin User',
    status: 'Posted',
    timestamp: new Date('2024-03-17T09:00:00'),
    notes: 'Stock count adjustment - physical count mismatch',
  },
  {
    id: '4',
    transactionId: 'TRX-2024-004',
    productId: '2',
    product: mockProducts[1],
    movementType: 'TRANSFER',
    sourceType: 'TRANSFER',
    quantity: 200,
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    locationId: '5',
    location: mockLocations[4],
    userId: 'user-3',
    userName: 'Logistics Manager',
    status: 'Posted',
    timestamp: new Date('2024-03-17T11:30:00'),
    notes: 'Transfer from WH-001 to WH-002',
  },
  {
    id: '5',
    transactionId: 'TRX-2024-005',
    productId: '4',
    product: mockProducts[3],
    movementType: 'INBOUND',
    sourceType: 'PURCHASE_ORDER',
    quantity: 500,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '2',
    location: mockLocations[1],
    referenceNumber: 'PO-2024-002',
    vendorId: '2',
    vendor: mockVendors[1],
    purchaseOrderId: '2',
    userId: 'user-2',
    userName: 'Warehouse Staff',
    status: 'Posted',
    timestamp: new Date('2024-03-18T08:45:00'),
    notes: 'Partial receiving from PO-2024-002',
  },
  {
    id: '6',
    transactionId: 'TRX-2024-006',
    productId: '6',
    product: mockProducts[5],
    movementType: 'INBOUND',
    sourceType: 'MANUAL',
    quantity: 300,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '4',
    location: mockLocations[3],
    referenceNumber: 'MANUAL-001',
    vendorId: '2',
    vendor: mockVendors[1],
    userId: 'user-1',
    userName: 'Admin User',
    status: 'Posted',
    timestamp: new Date('2024-03-18T10:00:00'),
    notes: 'Manual stock entry - legacy transaction migration',
  },
  {
    id: '7',
    transactionId: 'TRX-2024-007',
    productId: '8',
    product: mockProducts[7],
    movementType: 'OUTBOUND',
    sourceType: 'MANUAL',
    quantity: 15,
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    locationId: '6',
    location: mockLocations[5],
    referenceNumber: 'MANUAL-002',
    garmentId: '3',
    garment: mockGarments[2],
    userId: 'user-2',
    userName: 'Warehouse Staff',
    status: 'Posted',
    timestamp: new Date('2024-03-18T15:30:00'),
    notes: 'Manual outbound - old delivery order from previous system',
  },
  {
    id: '8',
    transactionId: 'TRX-2024-008',
    productId: '7',
    product: mockProducts[6],
    movementType: 'INBOUND',
    sourceType: 'MANUAL',
    quantity: 100,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '1',
    location: mockLocations[0],
    referenceNumber: 'MANUAL-003',
    vendorId: '5',
    vendor: mockVendors[4],
    userId: 'user-1',
    userName: 'Admin User',
    status: 'Draft',
    timestamp: new Date('2024-03-19T09:00:00'),
    notes: 'Pending stock entry - awaiting verification',
  },
  {
    id: '9',
    transactionId: 'TRX-2024-009',
    productId: '3',
    product: mockProducts[2],
    movementType: 'ADJUSTMENT',
    sourceType: 'ADJUSTMENT',
    quantity: 10,
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    locationId: '3',
    location: mockLocations[2],
    adjustmentReason: 'Found missing stock',
    userId: 'user-1',
    userName: 'Admin User',
    status: 'Draft',
    timestamp: new Date('2024-03-19T11:00:00'),
    notes: 'Positive adjustment - found unreported stock',
  },
];

// Mock Receivings
export const mockReceivings: Receiving[] = [
  {
    id: '1',
    purchaseOrderId: '2',
    purchaseOrder: mockPurchaseOrders[1],
    receivingDate: new Date('2024-03-12'),
    receiverName: 'Warehouse Staff',
    items: [
      { id: '1', poItemId: '3', productId: '4', product: mockProducts[3], expectedQuantity: 1000, receivedQuantity: 500, rejectedQuantity: 0, status: 'Partial' },
      { id: '2', poItemId: '4', productId: '6', product: mockProducts[5], expectedQuantity: 2000, receivedQuantity: 1000, rejectedQuantity: 50, status: 'Partial' },
    ],
    status: 'In Progress',
    notes: 'First batch received',
  },
  {
    id: '2',
    purchaseOrderId: '4',
    purchaseOrder: mockPurchaseOrders[3],
    receivingDate: new Date('2024-03-02'),
    receiverName: 'Admin User',
    items: [
      { id: '3', poItemId: '6', productId: '3', product: mockProducts[2], expectedQuantity: 200, receivedQuantity: 200, rejectedQuantity: 0, status: 'Received' },
    ],
    status: 'Completed',
  },
];

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalStock: 4765,
  incomingGoods: 156,
  outgoingGoods: 89,
  activePO: 3,
  activeDO: 2,
  lowStockAlerts: 2,
  warehouseCapacity: 23000,
  warehouseUsed: 15200,
};

// Recent Activities
export const mockRecentActivities: RecentActivity[] = [
  { id: '1', type: 'inbound', description: 'Received 500 pcs Zipper YKK from PO-2024-002', timestamp: new Date('2024-03-18T08:45:00'), user: 'Warehouse Staff' },
  { id: '2', type: 'outbound', description: 'Shipped 30 meters Jersey Fabric for DO-2024-001', timestamp: new Date('2024-03-17T14:30:00'), user: 'Logistics Team' },
  { id: '3', type: 'po_created', description: 'New PO-2024-003 created for Pack Solution', timestamp: new Date('2024-03-17T10:00:00'), user: 'Procurement' },
  { id: '4', type: 'adjustment', description: 'Stock adjustment: -5 pcs Hoodie Blank', timestamp: new Date('2024-03-17T09:00:00'), user: 'Admin User' },
  { id: '5', type: 'do_created', description: 'New DO-2024-002 created for Urban Style', timestamp: new Date('2024-03-16T16:00:00'), user: 'Sales Team' },
  { id: '6', type: 'inbound', description: 'Received 1000 pcs Button Metal from PO-2024-002', timestamp: new Date('2024-03-16T11:00:00'), user: 'Warehouse Staff' },
];

// Chart Data
export const stockByCategory: ChartData[] = [
  { name: 'Raw Materials', value: 2950 },
  { name: 'Accessories', value: 3500 },
  { name: 'Finished Goods', value: 170 },
  { name: 'Packaging', value: 800 },
];

export const monthlyMovement: ChartData[] = [
  { name: 'Jan', inbound: 1200, outbound: 800 },
  { name: 'Feb', inbound: 1500, outbound: 1100 },
  { name: 'Mar', inbound: 1800, outbound: 1300 },
  { name: 'Apr', inbound: 1400, outbound: 1000 },
  { name: 'May', inbound: 2000, outbound: 1600 },
  { name: 'Jun', inbound: 1700, outbound: 1400 },
];

export const warehouseCapacityData: ChartData[] = [
  { name: 'Main Warehouse', used: 7500, available: 2500 },
  { name: 'Secondary Warehouse', used: 3200, available: 1800 },
  { name: 'Distribution Center', used: 4500, available: 3500 },
];

export const poStatusData: ChartData[] = [
  { name: 'Draft', value: 1 },
  { name: 'Approved', value: 1 },
  { name: 'Partial Received', value: 1 },
  { name: 'Completed', value: 1 },
];

export const doStatusData: ChartData[] = [
  { name: 'Draft', value: 1 },
  { name: 'Picking', value: 1 },
  { name: 'Shipped', value: 1 },
];

// Aliases for cleaner imports
export const products = mockProducts;
export const vendors = mockVendors;
export const garments = mockGarments;
export const warehouses = mockWarehouses;
export const locations = mockLocations;
export const inventoryItems = mockInventoryItems;
export const stockMovements = mockStockMovements;

// Categories data
export const categories = [
  { id: '1', name: 'Raw Materials', code: 'RAW', description: 'Raw fabric and materials', productCount: 2, status: 'active' as const, createdAt: new Date('2024-01-10') },
  { id: '2', name: 'Accessories', code: 'ACC', description: 'Zippers, buttons, threads', productCount: 3, status: 'active' as const, createdAt: new Date('2024-01-12') },
  { id: '3', name: 'Finished Goods', code: 'FG', description: 'Ready-to-ship products', productCount: 2, status: 'active' as const, createdAt: new Date('2024-01-15') },
  { id: '4', name: 'Packaging', code: 'PKG', description: 'Boxes, bags, labels', productCount: 1, status: 'active' as const, createdAt: new Date('2024-02-01') },
];

// Movement Analytics for charts
export const movementAnalytics = [
  { month: 'Jan', inbound: 1200, outbound: 800 },
  { month: 'Feb', inbound: 1500, outbound: 1100 },
  { month: 'Mar', inbound: 1800, outbound: 1300 },
  { month: 'Apr', inbound: 1400, outbound: 1000 },
  { month: 'May', inbound: 2000, outbound: 1600 },
  { month: 'Jun', inbound: 1700, outbound: 1400 },
];

// Inbound Transactions
export const inboundTransactions = [
  {
    id: '1',
    transactionNumber: 'INB-2024-001',
    transactionDate: new Date('2024-03-15'),
    vendorId: '1',
    vendor: mockVendors[0],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Completed' as const,
    totalItems: 2,
    totalQuantity: 600,
    notes: 'Received from PO-2024-001',
    createdBy: 'Warehouse Staff',
    createdAt: new Date('2024-03-15'),
  },
  {
    id: '2',
    transactionNumber: 'INB-2024-002',
    transactionDate: new Date('2024-03-16'),
    vendorId: '2',
    vendor: mockVendors[1],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Completed' as const,
    totalItems: 2,
    totalQuantity: 1500,
    notes: 'Partial receiving from PO-2024-002',
    createdBy: 'Warehouse Staff',
    createdAt: new Date('2024-03-16'),
  },
  {
    id: '3',
    transactionNumber: 'INB-2024-003',
    transactionDate: new Date('2024-03-18'),
    vendorId: '1',
    vendor: mockVendors[0],
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    status: 'Pending' as const,
    totalItems: 1,
    totalQuantity: 200,
    notes: 'Awaiting quality check',
    createdBy: 'Admin User',
    createdAt: new Date('2024-03-18'),
  },
  {
    id: '4',
    transactionNumber: 'INB-2024-004',
    transactionDate: new Date('2024-03-19'),
    vendorId: '3',
    vendor: mockVendors[2],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Draft' as const,
    totalItems: 3,
    totalQuantity: 350,
    createdBy: 'Procurement',
    createdAt: new Date('2024-03-19'),
  },
];

// Outbound Transactions
export const outboundTransactions = [
  {
    id: '1',
    transactionNumber: 'OUT-2024-001',
    transactionDate: new Date('2024-03-16'),
    garmentId: '1',
    garment: mockGarments[0],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Completed' as const,
    totalItems: 2,
    totalQuantity: 230,
    notes: 'Shipped for DO-2024-001',
    createdBy: 'Logistics Team',
    createdAt: new Date('2024-03-16'),
  },
  {
    id: '2',
    transactionNumber: 'OUT-2024-002',
    transactionDate: new Date('2024-03-17'),
    garmentId: '2',
    garment: mockGarments[1],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Pending' as const,
    totalItems: 1,
    totalQuantity: 50,
    notes: 'Awaiting pickup',
    createdBy: 'Sales Team',
    createdAt: new Date('2024-03-17'),
  },
  {
    id: '3',
    transactionNumber: 'OUT-2024-003',
    transactionDate: new Date('2024-03-18'),
    garmentId: '3',
    garment: mockGarments[2],
    warehouseId: '2',
    warehouse: mockWarehouses[1],
    status: 'Completed' as const,
    totalItems: 1,
    totalQuantity: 15,
    createdBy: 'Logistics Team',
    createdAt: new Date('2024-03-18'),
  },
  {
    id: '4',
    transactionNumber: 'OUT-2024-004',
    transactionDate: new Date('2024-03-19'),
    garmentId: '4',
    garment: mockGarments[3],
    warehouseId: '1',
    warehouse: mockWarehouses[0],
    status: 'Draft' as const,
    totalItems: 2,
    totalQuantity: 100,
    createdBy: 'Sales Team',
    createdAt: new Date('2024-03-19'),
  },
];
